Multithreading
GopichandUlasalaEpam/DotNetMentoringProgram pull request #6
Opened 2023-05-16 13:44 UTC by GopichandUlasalaEpam

Task on MultiThreading is submitted.

2023-05-16 16:08 UTC, csreehari requested changes

2023-05-16 16:08 UTC, csreehari commented on MentorMultiThreading/MentorMultiThreading/Program.cs
> +            ThreadPool.QueueUserWorkItem(new WaitCallback(SumOperation), new LimitValues(midPoint, size));
```suggestion
            ThreadPool.QueueUserWorkItem(SumOperation, new LimitValues(0, midPoint));
            //SecondThread
            ThreadPool.QueueUserWorkItem(SumOperation, new LimitValues(midPoint, size));
```
could have simplified like above? See if this works. Same for below line as well.

2023-05-16 16:08 UTC, csreehari commented on MentorMultiThreading/MentorMultiThreading/Program.cs
> +        {
As per task, you should handle any exceptions that may occur during the program's execution. There is a potential chance of exception in this case

2023-05-16 16:08 UTC, csreehari commented on MentorMultiThreading/MentorMultiThreading/Program.cs
> +                resetEvent.Set();
It is not clear as to which thread is completed here, but as per task: 

> You should use a ManualResetEvent object to signal when each thread has finished its work.

2023-05-17 05:34 UTC, GopichandUlasalaEpam reviewed
Refactored the made changes by introducing exception handling and making threads to start one after another using manualresetevent

2023-05-17 05:38 UTC, closed without merging